npm install --save webpack
npm install --save webpack-cli
npm install --save react
npm install --save react-dom
npm install --save react-router-dom
npm install --save redux
npm install --save react-redux
npm install --save redux-logger
npm install --save @babel/core
npm install --save @babel/preset-env
npm install --save @babel/preset-react
npm install --save babel-loader
npm install --save lodash.merge
npm install --save redux-thunk